#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: "$0" [command]"
    exit 1
fi

case $1 in
    "start"  ) echo "Build server..."
               npm run build
               echo "Start server..."
               sudo systemctl daemon-reload;
               sudo systemctl enable seichi-compass-server.service;
               sudo systemctl start seichi-compass-server.service;;
    "stop"   ) echo "Stop server..."
               sudo systemctl stop seichi-compass-server.service;
               sudo systemctl disable seichi-compass-server.service;;
    "status" ) systemctl status seichi-compass-server.service;;
    "log"    ) journalctl -u seichi-compass-server.service;;
    *        ) echo "unknown command: "$1;;
esac
